"""블로그 플랫폼: 발행물, 태그, 시리즈, 소셜, 모더레이션

Revision ID: 0002_blog_platform
Revises: 0001_initial
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_blog_platform'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=40), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_index(op.f('ix_tags_post_count'), 'tags', ['post_count'], unique=False)
    op.create_table('follows',
    sa.Column('follower_id', sa.String(length=36), nullable=False),
    sa.Column('following_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('follower_id <> following_id', name='no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='unique_follow')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('POST', 'COMMENT', 'USER', name='reporttargettype'), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Enum('SPAM', 'ABUSE', 'SENSITIVE', 'COPYRIGHT', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'REJECTED', name='reportstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'target_type', 'target_id', name='unique_report')
    )
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index('ix_reports_target', 'reports', ['target_type', 'target_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='unique_series_slug_per_user')
    )
    op.create_table('user_blocks',
    sa.Column('blocker_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('blocker_id <> blocked_id', name='no_self_block'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=True),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'UNLISTED', 'HIDDEN', name='poststatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('comment_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='unique_post_slug_per_user')
    )
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_index('ix_posts_status_likes', 'posts', ['status', 'like_count'], unique=False)
    op.create_index('ix_posts_status_published', 'posts', ['status', 'published_at'], unique=False)
    op.create_index('ix_posts_user_status_published', 'posts', ['user_id', 'status', 'published_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_post_created', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id'),
    sa.UniqueConstraint('post_id', 'user_id', name='unique_post_like')
    )
    op.create_table('post_tags',
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='unique_post_tag')
    )
    op.create_table('series_posts',
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False, server_default='0'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'post_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('COMMENT', 'REPLY', 'LIKE', 'FOLLOW', name='notificationtype'), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=True),
    sa.Column('comment_id', sa.String(length=36), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.add_column('users', sa.Column('handle', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('post_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('follower_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_users_handle'), 'users', ['handle'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_handle'), table_name='users')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'follower_count')
    op.drop_column('users', 'post_count')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'handle')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('series_posts')
    op.drop_table('post_tags')
    op.drop_table('post_likes')
    op.drop_index('ix_comments_post_created', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_posts_user_status_published', table_name='posts')
    op.drop_index('ix_posts_status_published', table_name='posts')
    op.drop_index('ix_posts_status_likes', table_name='posts')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('user_blocks')
    op.drop_table('series')
    op.drop_index('ix_reports_target', table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('follows')
    op.drop_index(op.f('ix_tags_post_count'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###

